from database.cities import CITY
from database.services import SERVICE

cities = {
    CITY.FARMVILLE: [SERVICE.YARD_CARE_SERVICES, SERVICE.DECK_CLEANING_SERVICES, SERVICE.DRAIN_CLEANING],
    CITY.CHASE_CITY: [SERVICE.WALL_REPAIR_SERVICES, SERVICE._24_HOUR_PEST_CONTROL_SERVICES]
}
